# Development Database Configuration (e.g., H2 or Local MySQL)
spring.datasource.url=jdbc:h2:mem:library_dev;DB_CLOSE_DELAY=-1
spring.datasource.username=victor
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Server Port
server.port=8080