# Common Application Settings
spring.application.name=LibraryManagementSystem

# Set Default Active Profile (Change to 'prod' when deploying)
#spring.profiles.active=dev
spring.profiles.active=@activatedProperties@
spring.profiles.include=${spring.profiles.active}

# Force Hibernate Schema Validation to occur AFTER Liquibase bean setup is fully completed
spring.jpa.query.fail-on-pagination-over-collection-fetch=true

# Operational runtime engine logging levels
logging.level.liquibase=INFO
logging.level.org.liquibase.database=INFO