# Development Database Configuration (e.g., H2 or Local MySQL)
spring.datasource.url=jdbc:h2:mem:library_dev;DB_CLOSE_DELAY=-1
spring.datasource.username=victor
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# ???????? H2 ??????? ??? ?????? ???????? ????
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Server Port
server.port=8080

# Expose all actuator endpoints via HTTP
management.endpoints.web.exposure.include=*
# Show full database/health details
management.endpoint.health.show-details=always
# http://localhost:8080/actuator: Lists all available monitoring endpoints.
# http://localhost:8080/actuator/health: Shows application status (UP or DOWN).
# http://localhost:8080/actuator/metrics: Displays available system metrics (JVM memory, CPU usage, HTTP requests).

app.errors.show-details=true

# Tells our Java Initializer bean to pass "dev" to Liquibase
spring.liquibase.enabled=true