# Common Application Settings
spring.application.name=LibraryManagementSystem

# Set Default Active Profile (Change to 'prod' when deploying)
#spring.profiles.active=dev
spring.profiles.active=@activatedProperties@
spring.profiles.include=${spring.profiles.active}

# Force Hibernate Schema Validation to occur AFTER Liquibase bean setup is fully completed
spring.jpa.query.fail-on-pagination-over-collection-fetch=true

# Master-file path
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Active Profile Spring (for example, dev or prod) in the context of Liquibase
spring.liquibase.contexts=${spring.profiles.active}

# Operational runtime engine logging levels
logging.level.liquibase=INFO
logging.level.org.liquibase.database=INFO