--liquibase formatted sql

--changeset victor:1-create-tables
CREATE TABLE authors (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) NOT NULL UNIQUE,
                         description VARCHAR(250) NOT NULL
);

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE publishers (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NULL,
                       isbn VARCHAR(50) NOT NULL UNIQUE,
                       description VARCHAR(250) NOT NULL
);

CREATE TABLE books_authors (
                               book_id BIGINT NOT NULL,
                               author_id BIGINT NOT NULL,
                               PRIMARY KEY (book_id, author_id),
                               FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
                               FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE CASCADE
);

CREATE TABLE books_categories (
                                  book_id BIGINT NOT NULL,
                                  category_id BIGINT NOT NULL,
                                  PRIMARY KEY (book_id, category_id),
                                  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
                                  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE books_publishers (
                                  book_id BIGINT NOT NULL,
                                  publisher_id BIGINT NOT NULL,
                                  PRIMARY KEY (book_id, publisher_id),
                                  FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
                                  FOREIGN KEY (publisher_id) REFERENCES publishers(id) ON DELETE CASCADE
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);